#ifndef FIFI_SHARED_THEME_H
#define FIFI_SHARED_THEME_H

#define FIFI_THEME_API_VERSION 1u
#define FIFI_THEME_CONFIG_VERSION 1u
#define FIFI_THEME_CONFIG_PATH "/fifi-data/fifi-settings.conf"
#define FIFI_THEME_CONFIG_FORMAT_KEY "theme_format"
#define FIFI_THEME_KEY_ACCENT "accent"
#define FIFI_THEME_KEY_WALLPAPER "wallpaper"
#define FIFI_THEME_KEY_WALL_FIT "wall_fit"
#define FIFI_THEME_KEY_WALLPAPER_IMAGE "wallpaper_image"
#define FIFI_THEME_KEY_CLOCK_12H "clock_12h"
#define FIFI_THEME_KEY_ANIMATIONS "animations"
#define FIFI_THEME_KEY_STATUSBAR "statusbar"
#define FIFI_THEME_KEY_DESKTOP_INFO "desktop_info"
#define FIFI_THEME_KEY_UTC_OFFSET "utc_offset"
#define FIFI_THEME_KEY_PANEL_EDGE "panel_edge"
#define FIFI_THEME_KEY_PANEL_ALIGN "panel_align"
#define FIFI_THEME_KEY_PANEL_AUTOHIDE "panel_autohide"
#define FIFI_THEME_KEY_PANEL_SIZE "panel_size"
#define FIFI_THEME_KEY_DOCK_FLOAT "dock_float"
#define FIFI_THEME_KEY_FX_GLASS "fx_glass"
#define FIFI_THEME_KEY_FX_SHADOWS "fx_shadows"
#define FIFI_THEME_KEY_CORNER_RADIUS "corner_radius"
#define FIFI_THEME_KEY_FONT_FILE "font_file"
#define FIFI_THEME_KEY_FONT_PX "font_px"
#define FIFI_INPUT_KEY_MOUSE_SPEED "mouse_speed"
#define FIFI_INPUT_KEY_TOUCHPAD_SPEED "touchpad_speed"
#define FIFI_INPUT_DEFAULT_MOUSE_SPEED 0
#define FIFI_INPUT_DEFAULT_TOUCHPAD_SPEED 0
#define WALLPAPER_GRADIENT 0
#define WALLPAPER_SOLID 1
#define WALLPAPER_STARS 2
#define WALLPAPER_GRID 3
#define WALLPAPER_WAVES 4
#define WALLPAPER_IMAGE 5
#define WALLPAPER_AURORA 6
#define WALLPAPER_NORTHERN 7
#define WALLPAPER_NEBULA 8
#define WALLPAPER_DUSK 9
#define WALLPAPER_OCEAN 10
#define WALLPAPER_SPRING 11
#define WALLPAPER_EMBER 12
#define WALLPAPER_COUNT 13
#define WALLFIT_FILL 0
#define WALLFIT_FIT 1
#define WALLFIT_STRETCH 2
#define WALLFIT_CENTER 3
#define WALLFIT_COUNT 4
typedef enum { PANEL_BOTTOM = 0, PANEL_TOP = 1, PANEL_LEFT = 2, PANEL_RIGHT = 3 } panel_edge_t;
typedef enum { PALIGN_START = 0, PALIGN_CENTER = 1, PALIGN_END = 2 } panel_align_t;
#define FIFI_THEME_DEFAULT_ACCENT 0x00409cffu
#define FIFI_THEME_DEFAULT_WALLPAPER WALLPAPER_GRADIENT
#define FIFI_THEME_DEFAULT_WALL_FIT WALLFIT_FILL
#define FIFI_THEME_DEFAULT_CLOCK_12H 1
#define FIFI_THEME_DEFAULT_STATUSBAR 1
#define FIFI_THEME_DEFAULT_DESKTOP_INFO 1
#define FIFI_THEME_DEFAULT_PANEL_EDGE PANEL_BOTTOM
#define FIFI_THEME_DEFAULT_PANEL_ALIGN PALIGN_CENTER
#define FIFI_THEME_DEFAULT_PANEL_AUTOHIDE 0
#define FIFI_THEME_DEFAULT_PANEL_SIZE 0
#define FIFI_THEME_DEFAULT_DOCK_FLOAT 1
#define FIFI_THEME_DEFAULT_FX_GLASS 1
#define FIFI_THEME_DEFAULT_FX_SHADOWS 1
#define FIFI_THEME_DEFAULT_CORNER_RADIUS 9
#define FIFI_THEME_DEFAULT_FONT_PX 20
#define FIFI_ACCENT_PRESET_COUNT 16
#define FIFI_ACCENT_PRESETS { \
  0x003060c0u,0x00307830u,0x00802060u,0x00b04010u, \
  0x00408080u,0x00606020u,0x00204060u,0x00803030u, \
  0x00906010u,0x00208060u,0x00601880u,0x00107888u, \
  0x008040a0u,0x005bd9e3u,0x008f7bffu,0x00ff9a6bu }
#define FIFI_FONT_SIZES { 10,12,14,16,18,20,22,24,28,32,36,40,48 }
#endif
